sudo: required

language: generic

services: docker

before_install:
  - echo "starting create image"
  - docker build -t min/react -f Dockerfile.dev .

script:
  - docker run -e CI=true min/react npm run test -- --coverage

after_success:
  - echo "test success change"

deploy:
  provider: "elasticbeanstalk"
  region: "us-east-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-831395634681"
  bucket_path: "docker-react-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY